version: 1
updates:
  # Define your update schedule here (e.g., daily, weekly, etc.).
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "torch"
open-pull-requests-limit: 20   # maximum number of open pull requests at a time
    create:
      - security
