version: 2
updates:
  # Define your update schedule here (e.g., daily, weekly, etc.).
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "torch"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10   # maximum number of open pull requests at a time
      create:
        - security