name: Dependabot Auto Merge
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dependabot/auto-merge@v1
        with:
          token: ${{ secrets.SECRETS_GITHUB_TOKEN }}
          dependency-name: '*'
